//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.Versions = new HashSet<Versions>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid NamespaceId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public System.DateTime createdon { get; set; }
        public System.Guid createdby { get; set; }
    
        public virtual ICollection<Versions> Versions { get; set; }
        public virtual Namespaces Namespace { get; set; }
        public virtual Users CreatedUser { get; set; }
    }
}
