//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public System.Guid UserId { get; set; }
        public System.Guid RoleId { get; set; }
    
        public virtual Users User { get; set; }
        public virtual Roles Role { get; set; }
    }
}
