//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Roles = new HashSet<UserRoles>();
            this.ArticlesCreated = new HashSet<Articles>();
            this.CreatedVersions = new HashSet<Versions>();
        }
    
        public System.Guid id { get; set; }
        public string display { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<UserRoles> Roles { get; set; }
        public virtual ICollection<Articles> ArticlesCreated { get; set; }
        public virtual ICollection<Versions> CreatedVersions { get; set; }
    }
}
