//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versions
    {
        public System.Guid id { get; set; }
        public System.Guid ArticleId { get; set; }
        public System.DateTime createdon { get; set; }
        public int number { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Articles Article { get; set; }
        public virtual Users User { get; set; }
    }
}
